[wandb]
project = "jax-vs-pt"
name = "none"

[default]
proj_dir = "none"
data_dir = "none"

optim = "SGD"
lr = 0.1
momentum = 0.9
gamma=0.7
weight_decay = 5e-4
lr_scheduler = "StepLR(optimiser, step_size=2, gamma=0.7)"

epochs = 10
batch_size = 128
test_batch_size = 1024

[benchmarks]

[models]

[torch]
num_workers = 4
pin_memory = true

[JAX]

[MNIST]
epochs = 30
train_transform = """transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize([0.1307,], [0.3081,])
    ])"""
test_transform = """transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize([0.1307,], [0.3081,])
    ])"""

[CIFAR10]
epochs = 200
lr_scheduler = "CosineAnnealingLR(optimiser, T_max=200)"
train_transform = """transforms.Compose([
        transforms.ToTensor(),
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
    ])"""

test_transform = """transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
    ])"""

[IMAGENET]
